# Generated by Django 2.0.3 on 2018-06-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180614_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcategory',
            name='number',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
