# Generated by Django 2.0.3 on 2018-06-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20180614_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='correct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
