# Generated by Django 2.0.3 on 2018-06-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20180616_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='correct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
