# Generated by Django 2.0.3 on 2018-06-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20180616_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('NP', 'No preference'), ('E', 'easy'), ('M', 'medium'), ('H', 'hard')], default='NP', max_length=2),
        ),
    ]
