# Generated by Django 2.0.3 on 2018-06-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20180617_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('', 'No preference'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='', max_length=2),
        ),
    ]
