# Generated by Django 2.0.2 on 2018-06-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20180617_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('&', 'No preference'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='&', max_length=2),
        ),
    ]
