# Generated by Django 2.0.2 on 2018-06-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20180622_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('&', 'No preference'), ('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], default='&', max_length=1),
        ),
    ]
